/-
(C) 2026 Ralf Stephan, in collaboration with Claude Code.
Released under CC0 1.0 Universal (public-domain dedication).
See https://creativecommons.org/publicdomain/zero/1.0/
-/
import Challenge.Orbit

/-!
# Challenge, part 2: the cited inputs

The three cited axioms, and the definitions they and the Allouche–Shallit interface need.
Mirrors `CITED/AlloucheShallit{Basic,Complexity}.lean`, `CITED/SubspaceTheorem.lean`,
`CITED/AdamczewskiFaverjon.lean`, `CITED/CorvajaZannier{,Algebraic}.lean` and
`CITED/NairKumarRout.lean`.

Each axiom is stated here verbatim so that a reader sees exactly what is taken on faith.
Permitting an axiom by name in a config is not a loophole: comparator compares the types of
permitted axioms across both environments, so the solution cannot smuggle in a
`Subspace.evertseSchlickewei : False`.
-/

/-! ## Automatic sequences and subword complexity (Allouche–Shallit) -/

namespace AS

open ForMathlib.SubwordComplexity

section
/- `AS.kKernel` lives in a module whose imports stop short of Mathlib's algebra hierarchy,
so its `k ^ i` on `ℕ` elaborates to core's `instPowNat`.  Under `import Mathlib` the
`Monoid` route wins instead, and the two terms — though defeq — are not syntactically
identical, which comparator (rightly) reports as a mismatch.  Removing the three instances
on this section reproduces the development's elaboration exactly. -/
attribute [-instance] Monoid.toNPow NPow.toPow NPow.ofPow

/-- The **`k`-kernel** of a sequence `a : ℕ → ℕ`: the set of all subsequences `n ↦ a (kⁱ·n + r)`
for `i ≥ 0` and `0 ≤ r < kⁱ`. By Eilenberg's theorem, `a` is `k`-automatic iff this set is finite. -/
def kKernel (k : ℕ) (a : ℕ → ℕ) : Set (ℕ → ℕ) :=
  {s | ∃ i r, r < k ^ i ∧ s = fun n => a (k ^ i * n + r)}

/-- A sequence is **automatic** iff it is `k`-automatic for some base `k ≥ 2`, i.e. its `k`-kernel
is finite — equivalently, it is generated by a deterministic finite automaton with output. -/
def IsAutomatic (a : ℕ → ℕ) : Prop :=
  ∃ k, 2 ≤ k ∧ (kKernel k a).Finite

end

/-- The **subword complexity** `p_a(m)` of an infinite sequence: the number of distinct
length-`m` factors occurring at *any* position. -/
noncomputable def complexity (a : ℕ → ℕ) (m : ℕ) : ℕ := (Set.range fun n => factor a m n).ncard

end AS

/-! ## The Subspace Theorem (cited axiom [Sch91]) -/

namespace Subspace

variable {K : Type*} [Field K] [NumberField K]

/-- The local sup-norm `‖x‖_v = maxᵢ |x_i|_v` at a place `v`, as an `ℝ`-value. -/
noncomputable def localNorm {n : ℕ} (v : AbsoluteValue K ℝ) (x : Fin n → K) : ℝ :=
  ⨆ i, v (x i)

/-- The Subspace-Theorem double product `∏_{v∈S} ∏_i |L_{v,i}(x)|_v / ‖x‖_v`. -/
noncomputable def approxProduct {n : ℕ} (S : Finset (AbsoluteValue K ℝ))
    (L : AbsoluteValue K ℝ → Fin n → ((Fin n → K) →ₗ[K] K)) (x : Fin n → K) : ℝ :=
  ∏ v ∈ S, ∏ i, v (L v i x) / localNorm v x

/-- **The Subspace Theorem** (Schmidt, Theorem 1D′; Evertse–Schlickewei `S`-arithmetic
form): for a number field `K`, `n ≥ 2`, a finite place set `S`, per-place linearly
independent linear forms `L`, and `ε > 0`, the nonzero `x ∈ Kⁿ` with
`approxProduct S L x ≤ H(x)^{-n-ε}` lie in finitely many proper subspaces of `Kⁿ`.

**Cited axiom [Sch91].**  Both approximation theorems used in the kernel — the Main
Theorem of Corvaja–Zannier at `δ ∈ ℚ` and the repaired Nair–Kumar–Rout pair theorem — are
*derived* from this in the development, at `n = 2` and `n = 3` respectively; neither is
assumed. -/
axiom evertseSchlickewei {n : ℕ} (hn : 2 ≤ n)
    (S : Finset (AbsoluteValue K ℝ))
    (L : AbsoluteValue K ℝ → Fin n → ((Fin n → K) →ₗ[K] K))
    (hL : ∀ v ∈ S, LinearIndependent K (L v))
    (ε : ℝ) (hε : 0 < ε) :
    ∃ T : Finset (Submodule K (Fin n → K)),
      (∀ W ∈ T, W ≠ ⊤) ∧
      ∀ x : Fin n → K, x ≠ 0 →
        approxProduct S L x ≤ Height.mulHeight x ^ (-(n : ℝ) - ε) →
        ∃ W ∈ T, x ∈ W

end Subspace

/-! ## The Mahler-method alternative (cited axiom [AF17]) -/

namespace AF

/-- **[AF17] Corollaire 1.8**, in the specialization the development consumes: for an
automatic sequence `a` with bounded values and a rational `α` with `0 < |α| < 1`, the value
`f(α) = ∑ⱼ aⱼαʲ` is **either transcendental over `ℚ`, or rational**.

This is Adamczewski–Faverjon's own named case — Cobham's 1968 conjecture — with `k = ℚ`
forced by `α ∈ ℚ` and `a j ∈ ℕ ⊂ ℚ`.

**Cited axiom [AF17].**  Both disjuncts are real: the rational branch cannot be removed
(the paper's §8.1 exhibits a `{0,1}`-valued 3-automatic sequence realizing it), so this is
applied only where both branches die at once. -/
axiom transcendental_or_rat_of_automatic {a : ℕ → ℕ} {B : ℕ}
    (hbdd : ∀ j, a j ≤ B) (hauto : AS.IsAutomatic a)
    {α : ℚ} (hα0 : α ≠ 0) (hα1 : |α| < 1) :
    Transcendental ℚ (∑' j, (a j : ℝ) * (α : ℝ) ^ j) ∨
      ∃ r : ℚ, ∑' j, (a j : ℝ) * (α : ℝ) ^ j = (r : ℝ)

end AF

/-! ## Corvaja–Zannier: heights, values, pseudo-Pisot, and the algebraic-`δ` axiom -/

namespace CZ

/-- The absolute Weil height of `2^x·3^y ∈ ℚ*`: `max(numerator, denominator)` of the
reduced fraction, explicitly `max (2^{x⁺}·3^{y⁺}) (2^{x⁻}·3^{y⁻})`. -/
def height23 (x y : ℤ) : ℕ :=
  max (2 ^ x.toNat * 3 ^ y.toNat) (2 ^ (-x).toNat * 3 ^ (-y).toNat)

section
/- `aroots` needs `[IsDomain ℂ]`, and under `import Mathlib` that resolves through
`IsDomain.of_isSimpleRing` rather than the `instIsDomain` the development's narrower
imports select.  The two are defeq but structurally distinct — and the difference is
invisible in the pretty-printed definition, since it hides inside the auxiliary
`CZ.IsPseudoPisot._proof_2`.  Removing the instance here restores the development's
elaboration. -/
attribute [-instance] IsDomain.of_isSimpleRing

/-- **Pseudo-Pisot** ([CZ04] Definition, p. 2): a real `α` with `|α| > 1`, algebraic over
`ℚ`, all of whose conjugates other than `α` itself have modulus `< 1`, and whose trace is a
rational integer. -/
def IsPseudoPisot (v : ℝ) : Prop :=
  1 < |v| ∧ IsAlgebraic ℚ v ∧
    (∀ z ∈ (minpoly ℚ v).aroots ℂ, z ≠ (v : ℂ) → ‖z‖ < 1) ∧
    ∃ n : ℤ, ((minpoly ℚ v).aroots ℂ).sum = (n : ℂ)

end

/-- The value `δ·q·u` of the Main Theorem under the exponent encoding `u = 2^x·3^y` of
`Γ = ⟨2, 3⟩`, for a *real* multiplier `δ`. -/
noncomputable def svalR (δ : ℝ) (q : ℕ) (x y : ℤ) : ℝ :=
  δ * q * ((2 : ℝ) ^ x * (3 : ℝ) ^ y)

/-- **The Corvaja–Zannier Main Theorem** ([CZ04] p. 2), specialized to `Γ = ⟨2, 3⟩ ≤ ℚ*`
(exponent-encoded, `d = 1`, `q ≥ 1`) with the multiplier `δ` real **algebraic**.

**Cited axiom [CZ04].**  A lane separate from `Subspace.evertseSchlickewei`; the `δ ∈ ℚ`
instance *is* derived from the Subspace Theorem in the development, which anchors this
transcription.  Carried only by the algebraic-multiplier results. -/
axiom pseudoPisot_approx_alg (δ : ℝ) (hδalg : IsAlgebraic ℚ δ) (hδ : δ ≠ 0)
    (ε : ℝ) (hε : 0 < ε) :
    {p : ℕ × ℤ × ℤ | 1 ≤ p.1 ∧
      1 < |svalR δ p.1 p.2.1 p.2.2| ∧
      ¬ IsPseudoPisot (svalR δ p.1 p.2.1 p.2.2) ∧
      0 < distToNearestInt (svalR δ p.1 p.2.1 p.2.2) ∧
      distToNearestInt (svalR δ p.1 p.2.1 p.2.2)
        < (height23 p.2.1 p.2.2 : ℝ) ^ (-ε) * (p.1 : ℝ) ^ (-1 - ε)}.Finite

end CZ
